ElektraInitiative/PermaplanT

doc/decisions/2d_drawing_lib.md, doc/decisions/backend_programming_language.md, doc/decisions/backend_web_framework.md, doc/decisions/ci_cd.md, doc/decisions/database.md, doc/decisions/frontend_programming_language.md, doc/decisions/frontend_ui_framework.md
This is a draft PR for feedback and checking over things.
Refers to issue #2 
Currently it holds following decisions regarding:
=> Decisions on the tech stack 

RELATED_APPS.md
Refers to issue #5 
draft PR for feedback and review
=> Related apps

doc/decisions/2d_drawing_lib.md, doc/decisions/backend_programming_language.md, doc/decisions/backend_web_framework.md, doc/decisions/ci_cd.md, doc/decisions/database.md, doc/decisions/frontend_programming_language.md, doc/decisions/frontend_ui_framework.md
@buenaflor can you have a look at the updated alternatives? Is there something new for you which you find worth considering?
What do you think about Rust Diesel?
I also did a few other clarifications (stable and not nightly Rust).
=> updates in decisions

doc/usecases/entry_list_seeds.md, doc/usecases/label_layer.md, doc/usecases/map_create_delete.md, doc/usecases/map_search.md, doc/usecases/map_timeline.md
Contains usecases for:
-  entry+list of which seeds the user has (for better selection of plants), including amount and expire dates (higher recommendation of using the seed if it expires soon)
-  searching of maps via keywords (including public maps of other users)
-  creation/deletion of map (deletion with undo for a month)
-  timeline: scroll bar (granularity month) and date field to change the time that is currently visible on the map
-  label layer
=> more usecases

doc/development_setup.md, doc/test_setup.md, doc/tests/README.md
I wasn't sure where to put test and dev setup so right now it's in the root of /doc
Also do you have suggestions on what to add to the dev setup?
=> test and dev setup

README.md, doc/decisions/2d_drawing_lib.md, doc/usecases/buy_seeds.md, doc/usecases/calender.md, doc/usecases/entry_list_seeds.md, doc/usecases/layers/plants_layer.md, doc/usecases/layers/trees_layer.md, doc/usecases/layers/warnings_layer.md, doc/usecases/layers_visibility.md, doc/usecases/map_create_delete.md
=> update of usecases

ci/Jenkinsfile, ci/build-scripts/build-backend.sh, ci/build-scripts/build-frontend.sh, doc/ci.md
=> CI: Build Stage

backend/Cargo.lock, backend/Cargo.toml, backend/src/config/db.rs, backend/src/config/mod.rs, backend/src/config/routes.rs, backend/src/controllers/seed_controller.rs, backend/src/controllers/seed_controller_tests.rs, backend/src/controllers/variety_controller.rs, backend/src/error.rs, backend/src/main.rs, backend/src/models/dto/new_seed_dto.rs, backend/src/models/dto/seed_dto.rs, backend/src/models/dto/variety_dto.rs, backend/src/models/response.rs, backend/src/models/seed.rs, backend/src/models/variety.rs, backend/src/server.rs, backend/src/services/seed_service.rs, backend/src/services/variety_service.rs
=> Backend code refactoring

backend/src/main.rs
=> use path normalization resolve #69

ci/Jenkinsfile, doc/ci.md
part of #37 
fixes #53 
fixes #37
=> ci: deploy to dev env

doc/meetings/2023_03_21.md
=> Polyculture progress report for meeting 2023-03-21

doc/meetings/2023_03_20_db_kick_off.md
=> doc: add meeting agenda

frontend/src/components/Form/SimpleFormInput.tsx, frontend/src/features/seeds/components/CreateSeedForm.tsx
=> Translate all labels and placeholders in seed form to english.

frontend/src/config/index.ts, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/features/seeds/routes/CreateSeed.tsx, frontend/src/main.tsx, frontend/src/utils/map-error-to-string.ts
This PR adds an interceptor to the axios response in case of an error, and maps the message to a more user friendly string.
=> fix(seeds): better error messages

backend/src/config/app.rs, backend/src/main.rs
=> backend: allow startup without .env resolves #127

.gitignore, backend/.gitignore, frontend/.gitignore, scraper/.gitignore
When exploring the project locally I noticed that `git` was picking up some files and directories generated by my ide.
To prevent this I generated a more extensive root `.gitignore` generated with [gitignore.io](https://www.toptal.com/developers/gitignore).
We had some java specific entries in there as well which I removed.
I also went through the `.gitignore` in the sub directories and removed the entries which should now be covered by the generated one.
I'm not sure whether a small addition like this needs documentation and a decision.
=> Add extensive root .gitginore

doc/usecases/polyculture/suggest_alternatives.md
As requested in https://github.com/ElektraInitiative/PermaplanT/pull/120 this is the use case for suggesting plants of high ecological value.
@markus2330 
Are there any more polyculture use cases I should work on?
=> Polyculture use case: suggest alternatives 

doc/ui_components/Button/SimpleButton.md, doc/ui_components/Form/CreatableSelectMenu.md, doc/ui_components/Form/SelectMenu.md, doc/ui_components/Form/SimpleFormInput.md, doc/ui_components/Header/PageTitle.md, doc/ui_components/Modal/ModalContainer.md, doc/ui_components/Modal/SimpleModal.md, doc/ui_components/TansparentBackground.md
The aim of this pull request is to improve the documentation in PermaplanTs frontend. 
=> Improve frontend documentation.

backend/src/model/entity/plants_impl.rs, backend/src/model/entity/seed_impl.rs, ci/Jenkinsfile, ci/build-scripts/build-backend.sh, ci/build-scripts/build-schema.sh, ci/container-images/permaplant-node/Dockerfile, ci/container-images/permaplant-rust/Dockerfile, doc/ci.md
We are now executing checks inside Docker containers.
The build process also happens inside containers, so we are only executing minimal tasks on the PermaplanT server (unstash and deploy); everything else is happening on the docker infrastructure.
This fixes #63.
For #98 we still need some kind of entry point for the tests.
:rocket: :rocket: :rocket:
=> CI Pipeline with Docker, Checks, etc.

.github/CONTRIBUTING.md, doc/meetings/2023_03_28.md
=> meeting notes 28.3.023

frontend/src/App.tsx
=> fixes #187

doc/architecture/glossary.md, doc/usecases/polyculture/add_plant_relationships.md
This should document the following use case from https://github.com/ElektraInitiative/PermaplanT/issues/1
> adding companions to database on different levels
=> Polyculture Use Case: Add Plant Relationships

backend/src/error.rs
This PR aims at providing better status codes when errors in the backend occur. 
=> better status codes on errors resolves #200

ci/Jenkinsfile
=> ci: pr, dev, prod

doc/usecases/polyculture/search_plants.md
This should document the following use case from https://github.com/ElektraInitiative/PermaplanT/issues/1
> searching plants, ranking according
=> Polyculture Use Case: Search Plants

doc/meetings/2023_03_30_polyculture.md
Here are the notes from today's polyculture meeting.
@markus2330
I created a sheet to gather relationships consistently.
It's linked in the meeting notes.
Please have a look at it.
If you think we can work with this I'll forward it to the other people.
I tried to minimize work when importing this and make adding or changing data as easy as possible.
To reduce duplication, spelling, casing, and whitespace errors I made a "Plants" sheet with full taxonomic information.
When adding relations all you have to do is select values from drop downs.
The currently entered data are just examples and of course not any real relationships.
=> Meeting notes: 30.03.2023 Polyculture

frontend/src/features/seeds/api/searchPlants.ts
=> fix: invalid url error

doc/usecases/polyculture/review_plant_relationships.md
This should document the following use case from https://github.com/ElektraInitiative/PermaplanT/issues/1
> reviewing companions in database (increasing confidence of companion indicators)
=> Polyculture Use Case: Review Plant Relationships

benchmarks/.gitignore, benchmarks/README.md, benchmarks/package-lock.json, benchmarks/package.json, benchmarks/playwright.config.js, benchmarks/tests/performance-audit.spec.js
=> Performance audit tool

ci/Jenkinsfile, frontend/.prettierignore, frontend/src/App.tsx, frontend/src/components/Form/CreatableSelectMenu.tsx, frontend/src/components/Form/PaginatedSelectMenu.tsx, frontend/src/features/landing_page/components/GeoMap.tsx, frontend/src/features/landing_page/components/PhotoGallery.tsx, frontend/src/features/landing_page/routes/LandingPage.tsx, frontend/src/features/seeds/api/createSeed.ts, frontend/src/features/seeds/api/findAllSeeds.ts, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/features/seeds/store/CreateSeedStore.ts, frontend/src/features/seeds/store/FindSeedsStore.ts, frontend/src/routes/Pages/Pages.tsx, frontend/src/routes/index.ts
=> CI: Checks for Frontend

doc/decisions/auth.md
=> 117 nextcloud integration decision - authentication

doc/usecases/layers/base_layer.md, doc/usecases/layers_alternatives.md, doc/usecases/map_undo_redo.md, doc/usecases/map_versioning.md, doc/usecases/polyculture/search_plants.md
=> further fixes in use cases

frontend/src/components/Form/PaginatedSelectMenu.tsx
This should fix the issue with dark text mentioned in #265
=> fix: add stylesConfig for PaginatedSelectMenu

frontend/tailwind.config.js
Blue shades should now closer match the tone used for the logo.
Resolves #264.
=> Adjusted blues in color theme

README.md
=> Fix location of mdbook preprocessor

doc/meetings/2023_04_18.md
=> 14.04.2023

frontend/src/config/i18n/@types/i18next.d.ts, frontend/src/config/i18n/de/pricing.json, frontend/src/config/i18n/en/pricing.json, frontend/src/config/i18n/index.ts, frontend/src/features/pricing_page/components/PricingOption.tsx, frontend/src/features/pricing_page/routes/PricingPage.tsx
This should fix the errors with the `t` function.
Please consider using this translation structure.
=> refactor(pricing): improvements to the translation structure

doc/usecases/nextcloud-circles.md
=> added circle use case

doc/architecture/context.md, doc/architecture/glossary.md, doc/usecases/map_timeline_event_view.md
This documents the following use case from #1
> show events in the timeline (adding+removing elements)
=> Use Case: Map Timeline Event View

doc/architecture/glossary.md, doc/decisions/backend_testing_strategy.md, doc/tests/README.md
=> backend testing strategy

doc/research/nextcloud_integration.md
Summary of my research regarding the Nextcloud API capabilities
=> added nextcloud integration research

doc/authors.md, doc/meetings/2023_04_25.md, doc/usecases/map_create_delete.md, doc/usecases/map_statistics.md, doc/usecases/map_versioning.md
=> Agenda 25.04.

doc/meetings/2023_05_02.md
=> 02.05.2023 meeting

doc/meetings/2023_04_27_db.md
=> add 2023_04_27_db.md

doc/architecture/database_schemata.md
Added table descriptions for maps, users and blossoms tables and updated the ER diagram to include them.
=> Add maps, users and blossoms DB schema and ER diagram

doc/decisions/search_plants.md
As requested in https://github.com/ElektraInitiative/PermaplanT/issues/258 I summarized my findings.
I have purposefully left the decision open and only described the three approaches.
=> Plant Search

doc/meetings/2023_05_09.md, doc/usecases/copy_paste_selection.md, doc/usecases/entry_list_seeds.md, doc/usecases/layers/base_layer.md, doc/usecases/layers/drawing_layer.md, doc/usecases/layers/plants_layer.md, doc/usecases/layers_visibility.md, doc/usecases/login.md, doc/usecases/map_create_delete.md, doc/usecases/map_timeline_date_range_selection.md, doc/usecases/map_timeline_event_view.md, doc/usecases/map_timeline_single_date_selection.md, doc/usecases/map_undo_redo.md, doc/usecases/polyculture/search_plants.md, doc/usecases/zoom.md
=> Agenda 9.5.2023

doc/usecases/gamification/ingredient_lists.md, doc/usecases/gamification/map_collaboration.md
This PR extends the first set of gamification use cases proposed in #105 and will henceforth be used to add additional gamification use cases.
=> gamification use cases

ci/Jenkinsfile
=> ci: load scraper data

doc/meetings/2023_05_16.md, doc/usecases/copy_paste_selection.md, doc/usecases/entry_list_seeds.md, doc/usecases/layers/plants_layer.md, doc/usecases/login.md, doc/usecases/map_timeline_single_date_selection.md
=> meeting 16.5.2023

doc/meetings/2023_05_16.md
=> Meeting notes/16.05.2023

doc/meetings/2023_05_23.md, doc/milestones.md, doc/usecases/README.md
=> Agenda for 23.5.2023

doc/decisions/backend_mail_client.md
The decision about sending mails from the backend as written in #2.
=> decision: mail client

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, doc/meetings/2023_05_30.md, doc/milestones.md
=> 30.05.2023 Meeting

doc/database/schemata.md
Added table descriptions for the ingredient list use case, events, favourite groups and plant companions.
Also updated the ER diagram respectively.
Resolves #129.
=> Added more table definitions and ER diagrams

.github/CONTRIBUTING.md, backend/src/controller/config.rs, backend/src/controller/plantings.rs, backend/src/main.rs, backend/src/model/dto.rs, doc/architecture/01goals.md, doc/architecture/04solution.md, doc/architecture/07deployment.md, doc/architecture/08concepts.md, doc/architecture/09decisions.md, doc/architecture/10quality.md, doc/architecture/11risks.md, doc/architecture/README.md, doc/guidelines/api.md, doc/guidelines/logging.md, doc/install.md, doc/milestones.md, doc/mockups/README.md, doc/related.md, doc/ui_components/README.md
=> architecture, part II

frontend/src/components/Button/IconButton.stories.tsx, frontend/src/components/Button/IconButton.tsx, frontend/src/components/Button/SimpleButton.tsx, frontend/src/components/Card/InfoMessage.stories.tsx, frontend/src/components/Card/InfoMessage.tsx, frontend/src/components/Card/SimpleCard.stories.tsx, frontend/src/components/Card/SimpleCard.tsx, frontend/src/components/Form/CreatableSelectMenu.stories.tsx, frontend/src/components/Form/CreatableSelectMenu.tsx, frontend/src/components/Form/PaginatedSelectMenu.tsx, frontend/src/components/Form/SearchInput.stories.tsx, frontend/src/components/Form/SearchInput.tsx, frontend/src/components/Form/SelectMenu.tsx, frontend/src/components/Form/SelectMenuTypes.d.ts, frontend/src/components/Layout/Footer.stories.tsx, frontend/src/components/Layout/Footer.tsx, frontend/src/components/Layout/NavContainer.stories.tsx, frontend/src/components/Layout/Navbar.stories.tsx, frontend/src/components/Layout/PageLayout.stories.tsx, frontend/src/components/Layout/PageLayout.tsx, frontend/src/components/Layout/WidePageLayout.stories.tsx, frontend/src/components/Layout/WidePageLayout.tsx, frontend/src/components/Modals/ImageModal.stories.tsx, frontend/src/components/Modals/ImageModal.tsx, frontend/src/components/Modals/ModalContainer.tsx, frontend/src/components/Modals/SimpleModal.stories.tsx, frontend/src/components/Modals/SimpleModal.tsx, frontend/src/components/TransparentBackground.tsx, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/utils/enum.ts
I added documentation to every component I felt I knew enough about.
Please add or fix the documentation for the components which are created by you.
There is still an issue with the story of CreatableSelectMenu I don't know how to fix.
=> 333 basic component documentation

doc/meetings/2023_06_13.md, doc/usecases/current/base_layer.md, doc/usecases/current/landing_page.md, doc/usecases/current/landing_page_news.md, doc/usecases/current/map_creation.md
=> tasks for 9.6.2023

backend/migrations/2023-06-13-102759_seed_owner/down.sql, backend/migrations/2023-06-13-102759_seed_owner/up.sql, backend/src/config/api_doc.rs, backend/src/config/routes.rs, backend/src/controller/mod.rs, backend/src/controller/planting_suggestions.rs, backend/src/controller/seed.rs, backend/src/model/dto.rs, backend/src/model/dto/new_seed_impl.rs, backend/src/model/dto/seed_impl.rs, backend/src/model/entity.rs, backend/src/model/entity/plants_impl.rs, backend/src/model/entity/seed_impl.rs, backend/src/service/mod.rs, backend/src/service/plants.rs, backend/src/service/seed.rs, backend/src/service/util.rs, backend/src/test/mod.rs, backend/src/test/pagination.rs, backend/src/test/planting_suggestions.rs, backend/src/test/seed.rs, backend/src/test/util.rs, backend/src/test/util/token.rs
=> feat: available seasonal plants

frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
Ref: #468 
Fixes the above issue.
=> Fix: coordinate rounding

.github/PULL_REQUEST_TEMPLATE.md, doc/architecture/04solution.md, doc/guidelines/database.md, frontend/README.md
=> Architecture Documentation Part IV

frontend/src/config/i18n/de/maps.json, frontend/src/config/i18n/en/maps.json, frontend/src/features/maps/routes/MapCreateForm.tsx
Similar to the GeoMap on the landing page, the location picker map now also only loads on button press.
=> Updated location picker to only load on user click

ci/build-scripts/build-frontend.sh
=> ci: set VITE_NEXTCLOUD_URI [#486]

doc/architecture/04solution.md, doc/architecture/06runtime.md, doc/decisions/uuid.md, doc/guidelines/api.md, doc/guidelines/backend-logging.md, doc/guidelines/backend.md, doc/guidelines/code.md, doc/guidelines/database.md, doc/guidelines/frontend.md, doc/guidelines/versioning.md
=> Architecture Part V

.github/PULL_REQUEST_TEMPLATE.md, backend/Cargo.lock, backend/Cargo.toml, doc/CHANGELOG.md, doc/meetings/2023_06_27.md, doc/usecases/assigned/README.md, doc/usecases/assigned/add_plant_relationships.md, doc/usecases/assigned/geo_map.md, doc/usecases/assigned/map_collaboration.md, doc/usecases/assigned/map_statistics.md, doc/usecases/assigned/map_timeline_event_view.md, doc/usecases/assigned/map_timeline_range_selection.md, doc/usecases/assigned/new_member_notification.md, doc/usecases/current/layers_alternatives.md, doc/usecases/done/layers_visibility.md, frontend/package.json
=> meeting on 27.6

frontend/package-lock.json, frontend/package.json, frontend/src/components/Form/CreatableSelectMenu.stories.tsx, frontend/src/features/map_planning/layers/plant/components/PlantListItem.stories.tsx, frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx, frontend/src/features/map_planning/layers/plant/components/PlantSuggestionList.stories.tsx, frontend/src/features/map_planning/layers/plant/components/PlantSuggestionList.tsx
Ref: #333 
This PR adds documentation for the following components in storybook 
=> Additional Component Documentation

doc/backend/04http_header.md
Add http header documentation.
Resolves #384.
=> add documentation about http headers used by the backend

doc/authors.md
=> Update authors.md for Moritz

doc/CHANGELOG.md, doc/meetings/2023_07_04.md, doc/usecases/README.md
=> meeting 4th of July

backend/src/controller/config.rs, backend/src/model/dto.rs
Returns the cargo.toml version from the config endpoint.
References #510.
=> return version from config endpoint

doc/usecases/assigned/buy_seeds.md, doc/usecases/assigned/contributing_member.md, doc/usecases/assigned/diversity_score.md, doc/usecases/assigned/event_notfication.md, doc/usecases/assigned/experimental_results.md, doc/usecases/assigned/map_honors.md, doc/usecases/assigned/map_specific_favorite_groups.md, doc/usecases/assigned/matchmaking.md, doc/usecases/assigned/plant_lore.md, doc/usecases/assigned/reward_preview.md
Unassigned UCs that are no longer in scope for my contribution to PermaplanT.
=> Unassigned use cases

doc/CHANGELOG.md, frontend/src/config/i18n/de/maps.json, frontend/src/config/i18n/en/maps.json, frontend/src/features/maps/components/MapCard.tsx
Added on-hover tooltips to the action buttons of the `MapCard` component, describing their functionality.
Disabled the map duplicate button, since its completion is out of scope for the upcoming milestone.
Resolves #536.
=> Hover tooltips for MapCard buttons

doc/research/nextcloud_integration.md
=> moved setup section from thesis to docs

doc/CHANGELOG.md, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
=> fix: wrong placement of plantings

frontend/src/config/axios/index.ts, frontend/src/features/auth/api/getAuthInfo.ts, frontend/src/features/map_planning/layers/plant/api/getSeasonalAvailablePlants.ts, frontend/src/features/map_planning/routes/MapWrapper.tsx
=> frontend: build all URLs through axios

backend/src/model/entity/plant_layer.rs, backend/src/test/plant_layer.rs, doc/CHANGELOG.md
=> fix: wrong plant in relation

doc/CHANGELOG.md, frontend/src/Providers.tsx, frontend/src/components/Layout/Footer.tsx, frontend/src/components/Layout/Navbar.tsx
=> Version number displayed on the navbar, moved github link to the footer

doc/meetings/2023_07_11.md
=> tasks for 7.7.2023

.github/PULL_REQUEST_TEMPLATE.md, book.toml, ci/container-images/permaplant-mdbook/Dockerfile, doc/CHANGELOG.md, doc/architecture/05building.md, doc/architecture/10quality.md, doc/database/hierarchy.md, doc/decisions/reversible_deletion.md, doc/guidelines/documentation.md, doc/meetings/2023_07_04.md, doc/research/nextcloud_integration.md, doc/usecases/README.md, doc/usecases/done/layers_visibility.md
#555 closed to change target branch. All links fixed, link checker can be integrated into CI.
The remaining links were actually way less effort than I thought, but the last link fix session scared me of finishing this ^^.
Looking forward to no more broken links inside the book.
Maybe open follow up issue to enable external link check.
Weird ci [error](https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/PR-604/6/pipeline/194)
=> CI: Mdbook link checker

doc/architecture/12glossary.md, doc/guidelines/ui.md, doc/usecases/assigned/habitats_layer.md, doc/usecases/assigned/hydrology_layer.md, doc/usecases/assigned/infrastructure_layer.md, doc/usecases/assigned/paths_layer.md, doc/usecases/assigned/suggest_plants.md, doc/usecases/assigned/terrain_layer.md, doc/usecases/assigned/trees_layer.md, doc/usecases/assigned/winds_layer.md, doc/usecases/assigned/zones_layer.md, doc/usecases/current/measuring_distance.md
=> Documentation/use cases/moritz

backend/Cargo.lock, backend/Cargo.toml, doc/CHANGELOG.md, frontend/package-lock.json, frontend/package.json
=> after 0.2.2 release

book.toml, doc/architecture/03context.md, doc/meetings/2022_12_16.md, doc/meetings/2023_03_14.md, doc/meetings/2023_03_21.md, doc/meetings/2023_04_04.md, doc/meetings/2023_04_11.md, doc/research/nextcloud_integration.md, doc/tests/protocols/README.md, doc/tests/protocols/template.md, doc/usecases/assigned/membership_application.md
Closes #615
I basically replaced all [ ] with ( ).
Maybe we should warn everyone beforehand to not use [ ] braces anymore in any markdown file, unless it's a link.
Should I write this to the changelog?
=> Enable warning-policy error in mdbook

doc/development_setup.md
=> Add ram requirements to dev setup

frontend/src/features/map_planning/components/BaseStage.tsx, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx, frontend/src/features/map_planning/layers/plant/api/getRelations.ts, frontend/src/features/map_planning/layers/plant/components/PlantLayerRelationsOverlay.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx, frontend/src/features/map_planning/layers/plant/hooks/useRelations.ts, frontend/src/features/map_planning/utils/Tooltip.ts
Ref: #435 
Implements the plant relation visuals
=> Plant Relations Visuals

doc/CHANGELOG.md, doc/authors.md, frontend/src/features/landing_page/components/Team.tsx
=> Added myself as teammember for #511

frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts
Error notification was falsely configured to also fire while the image requests are still loading.
Resolves #617.
=> Fix a bug where the image error toast would show unexpectedly

ci/container-images/permaplant-mdbook/Dockerfile, doc/backend/README.md
=> Lock mdbook summary version

doc/usecases/assigned/landing_page_news.md, doc/usecases/current/gain_blossoms.md, doc/usecases/draft/map_webcam.md
Fix another set of broken links.
closes #558 
=> Fix broken links

ci/Jenkinsfile, ci/container-images/permaplant-node/Dockerfile, doc/CHANGELOG.md, doc/development_setup.md, frontend/README.md
This needs more manual testing. 
fixes #395
=> CI: Check package-lock.json after install

ci/Jenkinsfile
=> Rethrow pipeline error in master builds

doc/CHANGELOG.md, frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts
=> fix: image loading state skipped

Makefile, ci/Jenkinsfile, ci/container-images/permaplant-mdbook/Dockerfile, doc/CHANGELOG.md, doc/Dockerfile
- Base image is bookworm now
- Image size reduced
- Build speed increased by over 2 minutes
- Versions pinned
- Moved inside doc folder for visibility and better documentation (we could later make it runnable and serve the docu)
Building was done on my machine one at a time, no cache except the first layer.
| Dockerfile        | Size   | Time to Build (seconds) | Base Image |
|-------------------|--------|------------------------|------------------------|
| Dockerfile Mdbook | 1.39 GB | 364.6s                 | Bookworm               |
[Here](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-524/35/pipeline)
| Dockerfile           | Size   | Time to Build (seconds) | Base Image |
|-------------------   |--------|------------------------|------------------------| …
=> CI: Optimized mdbook docker image 

.pre-commit-config.yaml, ci/Jenkinsfile, ci/Jenkinsfile.release, doc/CHANGELOG.md
=> Groovy linter/fixer/formatter added

doc/architecture/04solution.md
Ref: #670 
Changelog was handled by #547 
=> docs: add docs about zod, wording improvements

backend/src/controller/plant_layer.rs
Documentation on how to move and scale the heatmap in the frontend.
Resolves #649.
=> Heatmap documentation

ci/Jenkinsfile, doc/CHANGELOG.md
as wished in #687, closes #687
=> CI: Move clippy, remove check

backend/.sqlfluff, doc/CHANGELOG.md
=> finetune .sqlfluff to force upper- and lowercase

.github/PULL_REQUEST_TEMPLATE.md, doc/meetings/2023_07_25.md, doc/release.md, doc/usecases/done/map_creation.md
=> meeting 25.7.2023

doc/decisions/frontend_e2e_testing.md, doc/decisions/frontend_end_to_end_testing.md, doc/tests/README.md
A quick draft of the current frontend testing strategy/stack.
Let me know what you think.
Open for discussion, alternatives, suggestions etc.
@markus2330 @Bushuo @absurd-turtle @ThorbenStaufer
I also moved some stuff around in doc/tests.
Please tag anyone I forgot to tag from the frontend team.
=> End-to-end testing decision

doc/CHANGELOG.md, frontend/src/features/map_planning/components/image/PublicNextcloudKonvaImage.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx, frontend/src/features/nextcloud_integration/hooks/useImage.ts, frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts, frontend/src/features/nextcloud_integration/hooks/usePublicImage.tsx
=> Remove image loading errors when placing plant.

doc/CHANGELOG.md, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
=> Base layer right toolbar: add debouncing

doc/CHANGELOG.md, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
=> Base layer right toolbar: fix wrong value being assigned to scale input.

backend/.sqlfluff, backend/migrations/00000000000000_diesel_initial_setup/down.sql, backend/migrations/00000000000000_diesel_initial_setup/up.sql, backend/migrations/2023-07-01-152628_squashed_setup/down.sql, backend/migrations/2023-07-01-152628_squashed_setup/up.sql, backend/migrations/2023-07-03-164000_add_map_geometry/down.sql, backend/migrations/2023-07-03-164000_add_map_geometry/up.sql, backend/migrations/2023-07-04-190000_base_layer/down.sql, backend/migrations/2023-07-04-190000_base_layer/up.sql, backend/migrations/2023-07-11-095000_map_cascading_deletes/down.sql, backend/migrations/2023-07-11-095000_map_cascading_deletes/up.sql, backend/migrations/2023-07-12-143111_user_data/down.sql, backend/migrations/2023-07-12-143111_user_data/up.sql, backend/migrations/2023-07-21-085933_gain_blossoms/down.sql, backend/migrations/2023-07-21-085933_gain_blossoms/up.sql, doc/usecases/current/shade_layer.md, doc/usecases/done/grid.md, frontend/src/config/i18n/de/guidedTour.json, frontend/src/config/i18n/en/guidedTour.json
=> add comments about immutability to sql files

backend/src/model/dto.rs, backend/src/model/dto/plants_impl.rs, backend/src/model/enum/plant_spread.rs, backend/src/test/plant.rs, backend/src/test/planting_suggestions.rs, doc/CHANGELOG.md, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
=> 686 sizes of plant in map editor

doc/CHANGELOG.md, frontend/src/config/i18n/de/plantSearch.json, frontend/src/config/i18n/en/plantSearch.json, frontend/src/features/map_planning/layers/plant/components/PlantSearch.tsx
=> Plant search: add feedback on empty search result

doc/CHANGELOG.md, frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx, frontend/src/features/nextcloud_integration/components/PublicNextcloudImage.tsx
=> Show plant icons in search

doc/tests/manual/protocol.md, frontend/src/config/i18n/de/guidedTour.json, frontend/src/config/i18n/en/guidedTour.json, frontend/src/features/map_planning/components/Map.tsx, frontend/src/features/map_planning/utils/EditorTour.ts
=> Improve Tour for release 0.3

frontend/src/config/i18n/de/guidedTour.json, frontend/src/config/i18n/en/guidedTour.json
=> clarify purpose of gamification

doc/CHANGELOG.md, frontend/src/features/map_planning/components/BaseStage.tsx
=> Remove Step/History from map planning

e2e/features/map_creation.feature, e2e/pages/maps/create.py, e2e/steps/test_map_creation.py
This should fix #746
Also some other small cleanups refactorings.
=> E2E: Fix  failing map creation tests

ci/Jenkinsfile
Fixes #747 
Not sure if this is a good solution. Open to suggestions.
=> CI: Wait for pr db before running e2e tests

doc/CHANGELOG.md, frontend/src/features/map_planning/utils/EditorTour.ts
The text for "Plants Layer (2/17)" was shown at "Plants Layer (1/17)"
=> Fixed display of wrong step text

doc/meetings/2023_07_31.md, doc/release.md, doc/usecases/assigned/area_of_plants.md, doc/usecases/assigned/copy_paste_selection.md
=> meeting Monday 31.7.2023

doc/CHANGELOG.md, frontend/src/components/Modals/ExtendedModal.tsx, frontend/src/components/TransparentBackground.tsx, frontend/src/config/i18n/de/guidedTour.json, frontend/src/config/i18n/en/guidedTour.json, frontend/src/features/map_planning/components/Map.tsx, frontend/src/styles/guidedTour.css
User will be asked on cancellation, if they really want to complete the tour. Alternatively they can choose to continue the tour the next time or revert the cancel.
Follow-up issue for a minor bug introduced in this version: #752.
Resolves #738 and Fixes #752.
=> Added cancel confirmation to Guided Tour

Makefile, backend/Makefile, doc/CHANGELOG.md, e2e/.flake8, e2e/ReadMe.md, e2e/conftest.py, e2e/features/login_logout.feature, e2e/features/search_plants.feature, e2e/pages/abstract_page.py, e2e/pages/home.py, e2e/pages/login.py, e2e/pages/maps/create.py, e2e/pages/maps/edit.py, e2e/pages/maps/management.py, e2e/pages/maps/planting.py, e2e/steps/test_login_logout.py, e2e/steps/test_map_creation.py, e2e/steps/test_plant_search.py, frontend/src/features/map_planning/components/toolbar/LayerList.tsx, frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx, frontend/src/features/map_planning/layers/plant/components/PlantSearch.tsx
A small set of plant search tests. Lmk if any scenario is missing. I think this covers the basic idea.
=> E2E: plant search tests

doc/CHANGELOG.md, e2e/features/planting.feature, e2e/pages/maps/planting.py, e2e/steps/test_plant_search.py, e2e/steps/test_planting.py
Very basic planting e2e tests.
=> E2E: Planting tests

doc/CHANGELOG.md, frontend/src/features/map_planning/components/toolbar/Layers.tsx
=> commented out disabled buttons

doc/tests/manual/reports/230730.md, doc/tests/manual/reports/230803.md
=> v0.3.1 Manual tests

frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
=> fixed validation of scale and rotation

ci/Jenkinsfile
=> ci: rename permaplant service

.pre-commit-config.yaml, ci/Jenkinsfile, doc/CHANGELOG.md, e2e/README.md, e2e/clean_db.py, e2e/clean_run_test.sh, e2e/conftest.py, e2e/e2e.sh, e2e/features/map_creation.feature, e2e/features/search_plants.feature, e2e/features/undo_redo.feature, e2e/install.sh, e2e/pages/abstract_page.py, e2e/pages/constants.py, e2e/pages/home.py, e2e/pages/login.py, e2e/pages/maps/create.py, e2e/pages/maps/edit.py, e2e/pages/maps/management.py, e2e/pages/maps/planting.py, e2e/requirements.txt, e2e/steps/test_login_logout.py, e2e/steps/test_map_creation.py, e2e/steps/test_plant_search.py, e2e/steps/test_planting.py, e2e/steps/test_undo_redo.py, e2e/uninstall.sh, frontend/src/features/map_planning/components/BaseStage.tsx, frontend/src/features/map_planning/components/Map.tsx
Testing Undo/Redo with opencv images of the canvas.
Rebased on top of planting e2e tests #766 
I added mypy, flake8 and black commit hooks.
=> E2E: Undo/Redo tests

doc/CHANGELOG.md, e2e/README.md, e2e/conftest.py, e2e/features/base_layer.feature, e2e/mypy.ini, e2e/pages/maps/planting.py, e2e/steps/test_base_layer.py, e2e/steps/test_plant_search.py, e2e/steps/test_planting.py, e2e/steps/test_undo_redo.py, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
3 scenarios for testing the base layer.
- add background
- rotate background
- scale background
Also adds mypy config file for a bit stricter checks.
=> E2E: Base layer tests

doc/CHANGELOG.md, e2e/conftest.py, e2e/features/base_layer.feature, e2e/features/layer_visibility.feature, e2e/features/login_logout.feature, e2e/features/map_creation.feature, e2e/features/planting.feature, e2e/features/search_plants.feature, e2e/features/undo_redo.feature, e2e/pages/abstract_page.py, e2e/pages/home.py, e2e/pages/login.py, e2e/pages/maps/create.py, e2e/pages/maps/edit.py, e2e/pages/maps/management.py, e2e/pages/maps/planting.py, e2e/requirements.txt, e2e/steps/common_steps.py, e2e/steps/test_base_layer.py, e2e/steps/test_layer_visibility.py, e2e/steps/test_login_logout.py, e2e/steps/test_map_creation.py, e2e/steps/test_plant_search.py, e2e/steps/test_planting.py, e2e/steps/test_undo_redo.py, frontend/src/features/map_planning/components/toolbar/LayerList.tsx
Testing layer visibility by toggling the visibility via the icon
The plant layer visibility is checked by clicking on the plant after toggling the visibility.
The base layer visibility is checked with taking a screenshot of the canvas prior toggling the visibility.
Rebased on base layer tests #777 
Introduced quite some refactoring here:
- object variables all prefixed with "_"
- extracted common steps into a separate file
- refactored gherkin syntax to make use as best possible from common steps
- removed worker id function since there was already an existing fixture doing the same
=> E2E: Layer visibility tests

doc/CHANGELOG.md, e2e/features/login_logout.feature, e2e/features/map_creation.feature, e2e/features/planting.feature, e2e/features/search_plants.feature, e2e/features/timeline.feature, e2e/features/undo_redo.feature, e2e/pages/maps/planting.py, e2e/steps/common_steps.py, e2e/steps/test_login_logout.py, e2e/steps/test_timeline.py
~~If you think less scenarios also solve the case, I would prefer that.~~
6 new scenarios for testing the timeline.
I hope they cover all possibilities, since we have `removed date`, `added date` and the `map date`, with each hiding/unhiding, should be 3^2 tests.
These tests are quite interestingly written and differ from the other tests, since they reuse many of the steps between each other.
Rebased on visibility tests #797
The real changes here are quite thin when the visibility tests get merged to master.
=> E2E: Timeline tests

doc/meetings/2023_08_08.md
=> add tasks 2.8 and 4.8

doc/meetings/2023_07_31.md
=> Mdbook: Fix indentation

book.toml, doc/CHANGELOG.md
This folds all chapters on the left side nav bar.
From [here](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#outputhtmlfold).
=> Mdbook fold all chapters

doc/changelog.md, frontend/src/components/Layout/Navbar.tsx
=> Seed link in navbar

.pre-commit-config.yaml, ci/Jenkinsfile
=> Fix pre-commit groovy linter

doc/changelog.md, e2e/README.md, e2e/conftest.py, e2e/features/base_layer.feature, e2e/features/layer_visibility.feature, e2e/features/map_creation.feature, e2e/features/planting.feature, e2e/features/search_plants.feature, e2e/features/timeline.feature, e2e/features/undo_redo.feature, e2e/pages/maps/create.py, e2e/steps/common_steps.py, e2e/steps/test_base_layer.py, e2e/steps/test_planting.py
Add worker uuids
Also refactor map names to be more readable
=> E2E: Add worker uuids

doc/changelog.md, doc/usecases/current/plants_layer.md, doc/usecases/done/map_timeline_single_selection.md
=> Uc-timeline-single-done

.pre-commit-config.yaml, ci/Jenkinsfile, ci/scripts/check-changelog.sh, ci/scripts/check-pre-commit.sh, doc/changelog.md
=> CI: Check changelog

doc/ci.md
closes #844
mentions about test results an reports in documentation, closes #806
=> Update CI docu

ci/Jenkinsfile, doc/changelog.md
Closes #859 
This is not the best fix, but the fastest.
I would like to put the conditional logic outside of the function runDock(), but would need a bit more playing around with the parallel() construct.
=> Skip changelog stage in master

doc/changelog.md, frontend/src/features/map_planning/components/BaseStage.tsx
=> Bug fix/817 middle mouse dragging and selection

.github/PULL_REQUEST_TEMPLATE.md, doc/changelog.md, doc/meetings/2023_09_04.md, doc/usecases/assigned/area_of_plants.md, doc/usecases/assigned/map_deletion.md, doc/usecases/assigned/map_honors.md
=> meeting 04.09.2023

doc/changelog.md, frontend/src/features/seeds/components/CreateSeedForm.tsx
After and edit, the plant of a seed would be set to indian abelia instead of the previously selected plant. 
=> Fx error where seeds would be set to wrong plant after edit.

doc/changelog.md, e2e/features/undo_redo.feature, e2e/pages/maps/planting.py, e2e/steps/test_undo_redo.py
Test for #887 
I couldnt use the new e2e test for the bisection because some common steps where missing and I did not want to move them around in every commit so I tested it manually in ~7 steps.
=> Undo plant deletion test

doc/changelog.md, doc/ci.md
@tschawax review from #846.
Thank you for these improvements.
=> Update CI doc

doc/changelog.md, frontend/src/features/map_planning/components/BaseStage.tsx, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx, frontend/src/features/map_planning/layers/plant/components/PlantSearch.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx, frontend/src/features/map_planning/utils/ShapesSelection.ts, frontend/src/features/map_planning/utils/planting-utils.test.ts, frontend/src/features/map_planning/utils/planting-utils.ts
=> Various bug fixes for plant selection, plant placement and select box during placement mode

doc/changelog.md, frontend/src/config/i18n/de/seeds.json, frontend/src/config/i18n/en/seeds.json, frontend/src/features/seeds/components/CreateSeedForm.tsx
=> Fix seed form validation bugs

doc/changelog.md, frontend/src/features/seeds/components/SeedsOverviewList.tsx, frontend/src/hooks/useTranslateQuality.ts, frontend/src/hooks/useTranslateQuantity.ts
=> Translate quality and quantity in seed overview

doc/changelog.md, frontend/src/features/map_planning/components/BaseStage.tsx, frontend/src/features/map_planning/hooks/useSelectedLayerVisibility.test.ts, frontend/src/features/map_planning/hooks/useSelectedLayerVisibility.ts
=> Bug fix/805 select invisible plant

.github/PULL_REQUEST_TEMPLATE.md, doc/changelog.md, doc/meetings/2023_09_11.md, doc/usecases/current/copy_paste_selection.md
=> meeting agenda for 11.9.2023

doc/tests/manual/reports/230915.md
=> Manual tests for 3.3

backend/src/model/entity/seed_impl.rs, backend/src/test/seed.rs, doc/changelog.md
=> Fix seed order by expiry date.

README.md, doc/changelog.md, e2e/.env.sample, e2e/README.md
Closes #898 
I did not want to overengineer this, so I did not add separate .bat scripts for windows.
I'm not really sure what the desired solution for this would be.
- Added more env variables
- Put env defaults into readme
- Mentions python and pip installation
- Hint for windows users
=> Reduce E2E entry barriers

ci/Jenkinsfile, doc/changelog.md
=> Tag docker images

doc/changelog.md, frontend/src/components/ExtendedPlantDisplay.tsx
=> Fix order of name parts in plant name.

doc/changelog.md, frontend/src/features/seeds/components/CreateSeedForm.tsx
=> Make plant name in select menu consistent with seed overview.

doc/changelog.md, frontend/src/features/seeds/components/SeedsOverviewList.tsx
=> Fix harvest year column title wrapping inappropriately.

doc/changelog.md, doc/usecases/current/entry_list_seeds.md
=> Add seed search to use case.

doc/changelog.md, frontend/src/components/Form/SimpleFormTextArea.tsx, frontend/src/features/seeds/components/CreateSeedForm.tsx
=> Fix text area only allowing one line of text in create seed menu.

doc/changelog.md, doc/meetings/2023_09_25.md
=> Meeting notes/25.09.2023

doc/changelog.md, doc/meetings/2023_10_02.md
=> 02.10.2023 meeting notes

backend/migrations/2023-09-20-073850_unique_seeds/down.sql, backend/migrations/2023-09-20-073850_unique_seeds/up.sql, backend/src/error.rs, backend/src/service/seed.rs, backend/src/test/layers.rs, doc/changelog.md, frontend/src/config/i18n/de/seeds.json, frontend/src/config/i18n/en/seeds.json, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/features/seeds/routes/CreateSeed.tsx, frontend/src/features/seeds/routes/EditSeed.tsx
=> Additional seed constraints

doc/changelog.md, doc/meetings/2023_10_09.md, doc/usecases/assigned/reward_preview.md
=> Meeting notes/09.10.2023

doc/changelog.md, frontend/src/config/i18n/de/guidedTour.json, frontend/src/config/i18n/en/guidedTour.json, frontend/src/features/map_planning/utils/EditorTour.ts
This step became obsolete after the search bar behaviour was changed.
Closes #955
=> fix: guided tour dead end at step 8 of plants layer

doc/changelog.md, doc/decisions/frontend_state_management.md
Added Persist middleware and its partialize method.
References #957
=> docs: update zustand documentation

ci/Jenkinsfile.release, doc/changelog.md
Smh `make doc-mdbook` is not the right command because it also does `make install-mdbook` and that doesnt work in the docker image.
`mdbook build` should be the solution
=> Fix mdbook build in release pipeline

backend/Cargo.toml, frontend/package.json
I forgot to pump the versions in #928
=> Pump versions to 0.3.5

doc/changelog.md, frontend/package-lock.json
I forgot to run npm install after increasing the version (:
=> Pump package-lock-json

doc/changelog.md, doc/guidelines/frontend-locators.md, e2e/pages/maps/create.py, e2e/pages/maps/planting.py, e2e/steps/test_map_creation.py, frontend/src/components/Form/PaginatedSelectMenu.tsx, frontend/src/components/Form/SearchInput.tsx, frontend/src/components/Form/SelectMenu.tsx, frontend/src/components/Form/__snapshots__/PaginatedSelectMenu.test.tsx.snap, frontend/src/components/Form/__snapshots__/SearchInput.test.tsx.snap, frontend/src/components/Form/__snapshots__/SelectMenu.test.tsx.snap, frontend/src/features/landing_page/components/LanguageSwitcher.tsx, frontend/src/features/map_planning/components/BaseStage.tsx, frontend/src/features/map_planning/components/Map.tsx, frontend/src/features/map_planning/components/toolbar/LayerListItem.tsx, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx, frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx, frontend/src/features/map_planning/layers/plant/components/PlantSearch.tsx, frontend/src/features/maps/components/MapCard.tsx, frontend/src/features/maps/routes/MapCreateForm.tsx, frontend/src/features/seeds/components/CreateSeedForm.tsx
=> Refactor data-testid's and add other missing locators

doc/changelog.md, frontend/src/features/auth/components/LoginButton.tsx
=> feat: improve styling of login and logout button for both themes

doc/changelog.md, frontend/src/features/map_planning/components/toolbar/Toolbar.tsx
=> feat: improve vertical scrollbars of toolbars

doc/changelog.md, frontend/src/features/map_planning/components/Map.tsx
Refreshing page with cancel-confirmation dialog opened no more completes tour.
Closes #986
=> fix: cancel-confirmation dialog of guided tour

doc/changelog.md, frontend/src/features/map_planning/components/toolbar/Toolbar.tsx
=> feat: add horizontal scrolling ability to toolbars

doc/changelog.md, doc/decisions/frontend_timeline_concept.md
=> add decision for custom implemented components

doc/changelog.md, frontend/src/config/i18n/de/routes.json, frontend/src/config/i18n/de/seeds.json, frontend/src/config/i18n/en/plantAndSeedSearch.json, frontend/src/config/i18n/en/routes.json, frontend/src/config/i18n/en/seeds.json
=> Rename "Seeds" to "Inventory".

doc/changelog.md, frontend/src/features/map_planning/utils/EditorTour.ts
=> Bug fix/861 tour deleting plant on small screen

ci/Jenkinsfile, doc/changelog.md
=> Run E2E tests on dev.permaplant

doc/changelog.md, doc/database/hierarchy.md, doc/meetings/2023_10_23.md, doc/meetings/2023_10_30.md
=> Meeting notes/30.10.2023

doc/changelog.md, frontend/src/config/i18n/de/baseLayerForm.json, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx, frontend/src/features/nextcloud_integration/components/FileSelector.tsx, frontend/src/features/nextcloud_integration/components/FileSelectorModal.tsx, frontend/src/styles/globals.css
Render close icon as component and at the top right.
Add new optional heading to modal component.
Make file selector layout responsive.
Add various small design improvements.
Closes #1011
before:
after:
before:
after:
=> feat: improve UI and responsiveness of file selector

doc/changelog.md, frontend/src/components/Button/IconButton.tsx, frontend/src/features/map_planning/components/Map.tsx
Undo and redo icons are now greyed out and disabled when not available. Icons can now be declared as toolbox icons which adds toolbox specific design. Focus design is improved and less noisy now.
Closes #1025, closes #657
=> feat: add status indicative designs for toolbox icons

doc/changelog.md, frontend/src/features/nextcloud_integration/components/FileSelector.tsx, frontend/src/features/nextcloud_integration/components/FileSelectorModal.tsx
Improved responsiveness of file selector and its file list.
Closes #1026
=> feat: improve loading spinner in file selector

doc/changelog.md, frontend/src/config/i18n/de/grid.json, frontend/src/config/i18n/de/index.ts, frontend/src/config/i18n/de/plantings.json, frontend/src/config/i18n/de/toolboxTooltips.json, frontend/src/config/i18n/de/undoRedo.json, frontend/src/config/i18n/en/grid.json, frontend/src/config/i18n/en/index.ts, frontend/src/config/i18n/en/plantings.json, frontend/src/config/i18n/en/toolboxTooltips.json, frontend/src/config/i18n/en/undoRedo.json, frontend/src/features/map_planning/components/Map.tsx
=> feat: improve toolbox tooltip wordings and move them into single file

doc/changelog.md, frontend/src/components/Button/SimpleButton.tsx, frontend/src/components/Button/__snapshots__/SimpleButton.test.tsx.snap, frontend/src/components/Modals/__snapshots__/SimpleModal.test.tsx.snap
Destructive buttons like for plant deletion do no more look disabled in dark mode.
Closes #1029
=> feat: improve design of danger buttons in dark mode

doc/changelog.md, frontend/package-lock.json, frontend/package.json, frontend/src/components/Form/MarkdownEditor.tsx, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/styles/globals.css, frontend/tsconfig.json
=> add markdown editor for note field in seed form

doc/changelog.md, doc/meetings/2023_11_06.md, doc/usecases/assigned/copy_paste_within_same_map.md, doc/usecases/assigned/map_collaboration.md, doc/usecases/done/multi_select.md
=> Meeting notes/06.11.2023

doc/changelog.md, frontend/src/App.tsx, frontend/src/Providers.tsx, frontend/src/features/debugging/routes/Debug.tsx, frontend/src/features/map_planning/hooks/useTourStatus.tsx, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx, frontend/src/features/map_planning/layers/plant/components/SeedListItem.tsx, frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts, frontend/src/features/map_planning/layers/plant/hooks/useFindPlantFromSeedCallback.ts, frontend/src/features/map_planning/layers/plant/hooks/useFindSeedById.ts, frontend/src/features/map_planning/layers/plant/hooks/usePlantSearch.ts, frontend/src/features/map_planning/layers/plant/hooks/useSeasonalAvailablePlants.ts, frontend/src/features/map_planning/layers/plant/hooks/useSeedSearch.ts, frontend/src/features/map_planning/routes/MapWrapper.tsx, frontend/src/features/map_planning/utils/ReadOnlyModeContext.tsx, frontend/src/features/maps/routes/MapCreateForm.tsx, frontend/src/features/maps/routes/MapEditForm.tsx, frontend/src/features/maps/routes/MapOverview.tsx, frontend/src/features/nextcloud_integration/components/UploadFile.tsx, frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts, frontend/src/features/seeds/routes/CreateSeed.tsx, frontend/src/features/seeds/routes/EditSeed.tsx, frontend/src/features/seeds/routes/ViewSeeds.tsx, frontend/src/features/toasts/groupedToast.tsx, frontend/src/hooks/useSafeAuth.tsx, frontend/src/routes/index.ts, frontend/src/routes/types.ts
=> Fix repeated error toasts

.github/ISSUE_TEMPLATE/release.yml, backend/Cargo.lock, backend/Cargo.toml, doc/changelog.md, doc/tests/manual/reports/231111.md, frontend/package-lock.json, frontend/package.json
Changes to be made after releasing. Closes #1032
=> Post Release 0.3.5

doc/changelog.md, frontend/src/components/Form/SimpleFormInput.stories.tsx, frontend/src/components/Form/SimpleFormInput.test.tsx, frontend/src/components/Form/SimpleFormInput.tsx, frontend/src/config/i18n/de/baseLayerForm.json, frontend/src/config/i18n/en/baseLayerForm.json, frontend/src/features/map_planning/components/BaseStage.tsx, frontend/src/features/map_planning/components/timeline/Timeline.tsx, frontend/src/features/map_planning/layers/base/components/BaseLayerAttributeEditForm.tsx, frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx, frontend/src/features/map_planning/layers/base/components/DistanceMeasurementModal.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx, frontend/src/features/maps/routes/MapEditForm.tsx, frontend/src/features/nextcloud_integration/components/FileSelector.tsx, frontend/src/features/nextcloud_integration/components/chat.tsx, frontend/src/features/nextcloud_integration/hooks/useFileExists.ts, frontend/src/features/nextcloud_integration/hooks/useImage.ts, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/svg/icons/close.svg
=> Rework base layer form.

doc/changelog.md, doc/tests/manual/protocol.md, frontend/src/components/Slider/NamedSlider.tsx
=> fix bug by using percentage for slider fill instead of pixel values

doc/architecture/12glossary.md, doc/changelog.md, doc/guidelines/frontend-ui-usability.md, doc/meetings/2023_11_13.md, doc/usecases/done/multi_select.md
=> add agenda for 13.11.2023

doc/changelog.md, e2e/pages/abstract_page.py, e2e/pages/home.py, e2e/pages/maps/planting.py, frontend/src/features/auth/components/LoginButton.tsx, frontend/src/features/map_planning/components/timeline/Timeline.tsx, frontend/src/features/map_planning/layers/base/components/BaseLayerAttributeEditForm.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
=> E2E increase timeline/baselayer test stability

ci/Jenkinsfile.release, doc/changelog.md
Closes #647 
I did not really mark the code, as I didnt find it really helpful, so I rather did a small refactoring to reuse the functions from the other Jenkinsfile. The downside from reusing the functions right now is, that test mdbook and test frontend is executed in the release pipeline now, which wasnt before.
Maybe we can try this new release pipeline for #879, but I'm not 100% sure yet. Might be better for the release after, to get v3.3 out today.
=> Refactor duplicate code

doc/changelog.md, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx, frontend/src/features/map_planning/layers/plant/components/PlantCursor.tsx
I timeboxed the effort and implemented a basic plant icon which follows the cursor while planting.
=> implemented basic planting cursor icon

ci/Jenkinsfile.release, doc/changelog.md
Reverts ElektraInitiative/PermaplanT#906
=> Revert "Refactor duplicate code"

doc/changelog.md, frontend/src/config/keybindings/keybindings.json, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx, frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx, frontend/src/features/map_planning/layers/plant/hooks/useDeleteSelectedPlantings.ts, frontend/src/features/map_planning/utils/layer-utils.ts
=> feat: delete plants via DEL

doc/architecture/04solution.md, doc/architecture/12glossary.md, doc/backend/04http_header.md, doc/changelog.md, doc/guidelines/i18n.md, doc/meetings/2023_11_20.md, doc/usecases/assigned/area_of_plants.md, doc/usecases/assigned/buy_seeds.md, doc/usecases/assigned/map_collaboration.md, doc/usecases/current/area_of_plants.md, doc/usecases/done/search_plants.md
=> meeting notes for 20.11.2023

doc/changelog.md, frontend/src/Providers.tsx, frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts, frontend/src/features/map_planning/layers/plant/hooks/useFindPlantFromSeedCallback.ts, frontend/src/features/map_planning/layers/plant/hooks/useFindSeedById.ts, frontend/src/features/map_planning/layers/plant/hooks/usePlantSearch.ts, frontend/src/features/map_planning/layers/plant/hooks/useSeasonalAvailablePlants.ts, frontend/src/features/map_planning/layers/plant/hooks/useSeedSearch.ts
=> refactor: react query error handling using query cache

doc/changelog.md, frontend/src/features/map_planning/layers/plant/components/PlantLabel.tsx, frontend/src/features/map_planning/utils/MapLabel.tsx
=> fix: ref warning by using forwardRef

doc/backend/README.md, doc/changelog.md, doc/development_setup.md, doc/guidelines/frontend-ui-usability.md, doc/meetings/2023_12_04.md, doc/usecases/assigned/landscape_layer.md, doc/usecases/assigned/warnings_layer.md, doc/usecases/current/drawing_layer.md
=> Meeting notes/04.12.2023

doc/changelog.md, doc/development_setup.md, doc/guidelines/frontend-keyhandling.md, doc/meetings/2023_10_23.md, doc/meetings/2023_11_06.md
=> doc: fix markdown

doc/changelog.md, frontend/src/features/map_planning/layers/plant/components/SeedListItem.tsx, frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts, frontend/src/features/map_planning/layers/plant/hooks/useFindPlantFromSeedCallback.ts, frontend/src/features/seeds/api/findPlantById.ts, frontend/src/features/seeds/api/findSeedById.ts, frontend/src/features/seeds/components/SeedsOverviewList.tsx
=> Allow undefined parameters for findPlantById and findSeedById.

doc/changelog.md, scraper/src/insert_plant_relations.js, scraper/src/insert_plants.js
=> fix: scraper not reading .env.local files

doc/changelog.md, doc/meetings/2023_12_18.md, doc/usecases/current/drawing_layer.md
=> Meeting notes/18.12.2023

doc/changelog.md, doc/meetings/2023_12_27.md, doc/meetings/2024_01_02.md, doc/usecases/assigned/create_layers.md, doc/usecases/assigned/hydrology_layer.md, doc/usecases/assigned/warnings_layer.md, doc/usecases/current/drawing_layer.md
=> agenda 02.01.2024

doc/changelog.md, doc/meetings/2024_01_08.md
=> add agenda for 8.1.2024

doc/authors.md, doc/changelog.md, frontend/src/features/landing_page/components/Team.tsx
=> Add 'Christoph Schreiner' as a team member (landing page, authors.md)

Makefile, backend/migrations/2024-01-10-185614_planting_add_notes/down.sql, backend/migrations/2024-01-10-185614_planting_add_notes/up.sql, backend/src/config/api_doc.rs, backend/src/controller/plantings.rs, backend/src/model/dto/actions.rs, backend/src/model/dto/plantings.rs, backend/src/model/dto/plantings_impl.rs, backend/src/model/entity/plantings.rs, doc/changelog.md
=> Add notes to plantings in backend.

.github/PULL_REQUEST_TEMPLATE.md, doc/changelog.md, doc/meetings/2023_12_11.md, doc/meetings/2024_01_15.md, doc/usecases/README.md, doc/usecases/assigned/map_collaboration.md
=> Meeting notes/15.01.2024

backend/migrations/2024-01-22-232806_remove_variety_from_seeds/down.sql, backend/migrations/2024-01-22-232806_remove_variety_from_seeds/up.sql, backend/src/model/dto.rs, backend/src/model/dto/new_seed_impl.rs, backend/src/model/dto/seed_impl.rs, backend/src/model/entity.rs, backend/src/model/entity/seed_impl.rs, backend/src/test/seed.rs, doc/changelog.md
=> remove variety from seeds table and dtos

.github/PULL_REQUEST_TEMPLATE.md, doc/changelog.md, doc/guidelines/security.md, doc/guidelines/versioning.md, doc/meetings/2024_01_22.md, doc/usecases/assigned/create_layers.md, doc/usecases/assigned/fertilization_layer.md, doc/usecases/assigned/landscape_layer.md, doc/usecases/assigned/photo_layer.md, doc/usecases/current/drawing_layer.md, doc/usecases/draft/dimensioning_layer.md, doc/usecases/draft/infrastructure_layer.md, doc/usecases/draft/paths_layer.md
=> Meeting notes/22.01.2024

doc/changelog.md, doc/meetings/2024_01_29.md
=> add meeting agenda 29.01.2024

doc/changelog.md, doc/meetings/2024_02_12.md
=> Meeting notes/12.02.2024

doc/architecture/04solution.md, doc/changelog.md, doc/meetings/2024_02_19.md
=> add 19.02.2024 agenda

doc/changelog.md, frontend/src/config/i18n/de/guidedTour.json, frontend/src/config/i18n/de/index.ts, frontend/src/config/i18n/de/maps.json, frontend/src/config/i18n/de/plantRelations.json, frontend/src/config/i18n/en/guidedTour.json, frontend/src/config/i18n/en/index.ts, frontend/src/config/i18n/en/maps.json, frontend/src/config/i18n/en/plantRelations.json, frontend/src/features/map_planning/hooks/mapEditorHookApi.ts, frontend/src/features/map_planning/hooks/tourHookApi.ts, frontend/src/features/map_planning/layers/plant/hooks/plantHookApi.ts, frontend/src/features/map_planning/layers/plant/hooks/relationsHookApi.ts, frontend/src/features/maps/hooks/mapHookApi.ts, frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts, frontend/src/features/seeds/hooks/seedHookApi.ts
=> feat(#1136); add missing toast messages

doc/changelog.md, frontend/src/config/i18n/de/index.ts, frontend/src/config/i18n/de/keybindings.json, frontend/src/config/i18n/en/index.ts, frontend/src/config/i18n/en/keybindings.json, frontend/src/config/keybindings/index.ts, frontend/src/features/map_planning/layers/base/components/MapGeometryToolForm.tsx, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
=> feat(#1198): add tooltips for keybindings

doc/changelog.md, doc/decisions/frontend_polygon_libraries.md
=> add decicison for polygon libraries

Makefile, README.md, ci/Jenkinsfile, ci/Jenkinsfile.release, doc/changelog.md
=> 275 deploy documentation

backend/src/model/dto.rs, backend/src/model/dto/plants_impl.rs, backend/src/test/plant.rs, backend/src/test/util/data.rs, doc/changelog.md, frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx, frontend/src/features/map_planning/layers/plant/components/PlantLabel.tsx, frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx, frontend/src/features/map_planning/layers/plant/components/Planting/Planting.tsx, frontend/src/features/map_planning/layers/plant/components/Planting/utils.ts, frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx, frontend/src/features/map_planning/layers/plant/components/SeedListItem.tsx, frontend/src/features/seeds/components/CreateSeedForm.tsx, frontend/src/features/seeds/components/SeedsOverviewList.tsx, frontend/src/utils/plant-naming.test.tsx, frontend/src/utils/plant-naming.tsx
This PR fixes German common names not being used when the language is set to German for the following occurences of common plant names:
This fixes #433
=> Fixed German common names not being used when language is set to German

backend/migrations/2024-04-01-140032_add_drawing_layer_to_existing_maps/down.sql, backend/migrations/2024-04-01-140032_add_drawing_layer_to_existing_maps/up.sql, doc/changelog.md
=> Add migration that adds drawings layers to existing maps.

ci/Jenkinsfile, doc/changelog.md
This PR changes Jenkins so we only deploy the pr server on pr branches and not from the master branch anymore.
=> 1244 several master builds have failed

doc/changelog.md, frontend/src/features/landing_page/components/GeoMap.tsx
- The link to the "plant.svg" image used in openstreetmap was broken due to the SVGs previously being moved to a different location
- Fixed the link using an import statement
=> 1170 Fix import for svg used in openstreetmap

doc/changelog.md, doc/contrib/frontend.md, doc/guidelines/frontend-api-calls.md, doc/guidelines/frontend-locators.md, doc/guidelines/i18n.md, doc/meetings/2024_01_02.md, doc/meetings/2024_01_08.md, doc/meetings/2024_01_15.md, doc/meetings/2024_01_22.md, doc/meetings/2024_01_29.md, doc/meetings/2024_02_05.md, doc/meetings/2024_02_12.md, doc/meetings/2024_02_19.md, doc/research/nextcloud_integration.md
=> Fix documentation issues

doc/changelog.md, doc/tests/manual/reports/240410.md
=> did manual test for 0.3.7

doc/changelog.md, frontend/src/config/i18n/de/blog.json, frontend/src/config/i18n/en/blog.json, frontend/src/features/map_planning/utils/EditorTour.ts
=> 1180 0.3.7 release

backend/src/model/entity.rs, doc/changelog.md, doc/meetings/2024_04_08.md, doc/usecases/assigned/hydrology_layer.md
=> Meeting 8.4.2024

ci/Jenkinsfile.release, doc/changelog.md
=> fixed bug where cargo doc does not run in backend folder

backend/Cargo.lock, backend/Cargo.toml, doc/changelog.md, doc/tests/manual/reports/240410.md, frontend/package-lock.json, frontend/package.json
=> changed release from 0.3.7 ro 0.4.0

doc/changelog.md, frontend/src/__test_utils__/msw_handlers/plants.ts, frontend/src/features/map_planning/layers/plant/hooks/relationsHookApi.test.tsx, frontend/src/features/map_planning/layers/plant/hooks/useSelectPlantForPlanting.test.tsx
Some hooks used by layers in frontend are tested here using unit-tests.
=> Add tests for hooks in frontend/layers

doc/changelog.md, frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx, frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
=> Add warn signs to attributeEditForm for multi-selected plant-areas
